# Generated by Django 4.0 on 2023-05-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_workoutset_workoutplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='rest',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
