# Generated by Django 4.0 on 2023-05-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_workoutset_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='rest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
