# Generated by Django 4.2 on 2023-04-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exercise_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
